In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score,mean_squared_error
from math import sqrt
from sklearn import metrics

In [ ]:
df = pd.read_csv('credit_train.csv')
df.head()

Loan ID                           Customer ID  \
0  14dd8831-6af5-400b-83ec-68e61888a048  981165ec-3274-42f5-a3b4-d104041a9ca9   
1  4771cc26-131a-45db-b5aa-537ea4ba5342  2de017a3-2e01-49cb-a581-08169e83be29   
2  4eed4e6a-aa2f-4c91-8651-ce984ee8fb26  5efb2b2b-bf11-4dfd-a572-3761a2694725   
3  77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a  e777faab-98ae-45af-9a86-7ce5b33b1011   
4  d4062e70-befa-4995-8643-a0de73938182  81536ad9-5ccf-4eb8-befb-47a4d608658e   

  Loan Status  Current Loan Amount        Term  Credit Score  Annual Income  \
0  Fully Paid             445412.0  Short Term         709.0      1167493.0   
1  Fully Paid             262328.0  Short Term           NaN            NaN   
2  Fully Paid           99999999.0  Short Term         741.0      2231892.0   
3  Fully Paid             347666.0   Long Term         721.0       806949.0   
4  Fully Paid             176220.0  Short Term           NaN            NaN   

  Years in current job Home Ownership             Purpose  Monthly Debt  \
0              8 years  Home Mortgage   Home Improvements       5214.74   
1            10+ years  Home Mortgage  Debt Consolidation      33295.98   
2              8 years       Own Home  Debt Consolidation      29200.53   
3              3 years       Own Home  Debt Consolidation       8741.90   
4              5 years           Rent  Debt Consolidation      20639.70   

   Years of Credit History  Months since last delinquent  \
0                     17.2                           NaN   
1                     21.1                           8.0   
2                     14.9                          29.0   
3                     12.0                           NaN   
4                      6.1                           NaN   

   Number of Open Accounts  Number of Credit Problems  Current Credit Balance  \
0                      6.0                        1.0                228190.0   
1                     35.0                        0.0                229976.0   
2                     18.0                        1.0                297996.0   
3                      9.0                        0.0                256329.0   
4                     15.0                        0.0                253460.0   

   Maximum Open Credit  Bankruptcies  Tax Liens  
0             416746.0           1.0        0.0  
1             850784.0           0.0        0.0  
2             750090.0           0.0        0.0  
3             386958.0           0.0        0.0  
4             427174.0           0.0        0.0

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.head()

Loan ID  \
2   4eed4e6a-aa2f-4c91-8651-ce984ee8fb26   
6   273581de-85d8-4332-81a5-19b04ce68666   
8   8af915d9-9e91-44a0-b5a2-564a45c12089   
10  32c2e48f-1ba8-45e0-a530-9a6622c18d9c   
12  403d7235-0284-4bb6-919a-09402fecbf7b   

                             Customer ID Loan Status  Current Loan Amount  \
2   5efb2b2b-bf11-4dfd-a572-3761a2694725  Fully Paid           99999999.0   
6   90a75dde-34d5-419c-90dc-1e58b04b3e35  Fully Paid             217646.0   
8   af534dea-d27e-4fd6-9de8-efaa52a78ec0  Fully Paid             548746.0   
10  0de7bcdb-ebf4-4608-ba39-05f083f855b6  Fully Paid           99999999.0   
12  11581f68-de3c-49d8-80d9-22268ebb323b  Fully Paid           99999999.0   

          Term  Credit Score  Annual Income Years in current job  \
2   Short Term         741.0      2231892.0              8 years   
6   Short Term         730.0      1184194.0             < 1 year   
8   Short Term         678.0      2559110.0              2 years   
10  Short Term         728.0       714628.0              3 years   
12  Short Term         740.0       776188.0             < 1 year   

   Home Ownership             Purpose  Monthly Debt  Years of Credit History  \
2        Own Home  Debt Consolidation      29200.53                     14.9   
6   Home Mortgage  Debt Consolidation      10855.08                     19.6   
8            Rent  Debt Consolidation      18660.28                     22.6   
10           Rent  Debt Consolidation      11851.06                     16.0   
12       Own Home  Debt Consolidation      11578.22                      8.5   

    Months since last delinquent  Number of Open Accounts  \
2                           29.0                     18.0   
6                           10.0                     13.0   
8                           33.0                      4.0   
10                          76.0                     16.0   
12                          25.0                      6.0   

    Number of Credit Problems  Current Credit Balance  Maximum Open Credit  \
2                         1.0                297996.0             750090.0   
6                         1.0                122170.0             272052.0   
8                         0.0                437171.0             555038.0   
10                        0.0                203965.0             289784.0   
12                        0.0                134083.0             220220.0   

    Bankruptcies  Tax Liens  
2            0.0        0.0  
6            1.0        0.0  
8            0.0        0.0  
10           0.0        0.0  
12           0.0        0.0

In [ ]:
# X-independent,Y-dependent
x=df[['Annual Income','Current Credit Balance','Number of Open Accounts']]
y=df[['Monthly Debt']]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
x_train.shape

(29138, 2)

In [ ]:
x_test.shape

(7285, 2)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
print(model.coef_)
print(model.intercept_)

[[0.0056802  0.01128927]]
[7979.36089311]


In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred

array([[15961.98550268],
       [14601.0975261 ],
       [16197.50790089],
       ...,
       [23348.19002198],
       [19282.99045864],
       [15208.40124069]])

In [ ]:
Y_pred=y_pred.ravel()

In [ ]:
Y_pred

array([15961.98550268, 14601.0975261 , 16197.50790089, ...,
       23348.19002198, 19282.99045864, 15208.40124069])

In [ ]:
Y_pred.shape

(7285,)

In [ ]:
Y_test = y_test['Monthly Debt'].values
Y_test

array([14991.19, 19112.1 , 27303.57, ..., 31702.45, 24335.39, 10450.76])

In [ ]:
Y_test=Y_test.ravel()

In [ ]:
df=pd.DataFrame(Y_test,Y_pred)
df=pd.DataFrame({"Actual Montly debt":Y_test,'Predicted Monthly debt':Y_pred})
print(df)

      Actual Montly debt  Predicted Monthly debt
0               14991.19            15961.985503
1               19112.10            14601.097526
2               27303.57            16197.507901
3               30759.67            27818.295581
4               16461.98            13746.226570
...                  ...                     ...
7280             9092.45            18018.685042
7281            34362.07            58647.072236
7282            31702.45            23348.190022
7283            24335.39            19282.990459
7284            10450.76            15208.401241

[7285 rows x 2 columns]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
model.score(x_test,Y_test)*100

37.84685075211767

In [ ]:
trial = np.array([[1184194.0,122170.0]])
print("New Predicted: {}".format(model.predict(trial)))

New Predicted: [[16085.02694269]]


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
